### ISSUE TITLE
临界点的疑问

### ISSUE THREAD

**Issue by HZChenCheng** [ArchLL/PersonalCenter-Extend#10]
吸顶临界点(此时的临界点不是视觉感官上导航栏的底部，而是当前屏幕的顶部相对scrollViewContentView的位置).
关于这点不是想的很明白?能不能讲解一下!!!谢谢!!!

**Comment by ArchLL** [comment]
换句话说临界点就是mainTableView停止滚动的位置，mainTableView的contentView需要留出来一屏大小（这个要根据你实际需要调整，demo中是预留了一屏）用于你显示categoryView和pageViewControllers。

如果你还是不能理解，建议你看看demo运行过程中的层级结构
