### ISSUE TITLE
当有很多个分类的时候

### ISSUE THREAD

**Issue by Unchanged-Is-Changed** [ArchLL/PersonalCenter-Extend#11]
分类很多的时候,比如超过20个,本来选中的第一个,滑动后,后面的被选中了,
数量少的时候没有问题

**Comment by Unchanged-Is-Changed** [comment]
不好意思,描述不是很清楚
bug现象:CategoryView大概有20条数据的时候,游标会乱跑
下载下来调试找到原因了
更新游标那里的约束不能与cell直接建立,cell复用的时候导致游标乱跑
目前我是把cell的坐标转换出来再给游标加的约束,可以正常运行了
作者有时间修复下吧 😁😁😁😁

**Comment by ArchLL** [comment]
感谢反馈，已经解决
