### ISSUE TITLE
优化问题

### ISSUE THREAD

**Issue by meloanyang** [ArchLL/PersonalCenter-Extend#4]
在初始化
NSArray  *controllers = @[VC1];
NSArray  *titles = @[@"1"];
_segmentedPageViewController.pageViewControllers = controllers;
_segmentedPageViewController.categoryView.titles = titles;

在服务端请求后：
NSArray  *controllers = @[VC1,VC1,VC1];
NSArray  *titles = @[@"2",@"3",@"4"];
_segmentedPageViewController.pageViewControllers = controllers;
_segmentedPageViewController.categoryView.titles = titles;

此时显示还有1个，但标题改为@“2”了。

怎么优化？

**Comment by ArchLL** [comment]
已经优化，请更新到"0.1.8"版本
