### ISSUE TITLE
HGCenterBaseTableView为UICollectionView的情况

### ISSUE THREAD

**Issue by SeongBrave** [ArchLL/PersonalCenter-Extend#9]
能否增加一种HGCenterBaseTableView为UICollectionView的情况吗？我这边看了下源码，UITableView能加的tablefooterview上，但是UICollectionView不知道能加到哪呢?能给个意见吗

**Comment by ArchLL** [comment]
可以加到cell上

**Comment by SeongBrave** [comment]
@ArchLL 我现在加到cell可以了，但是现在有个问题，uicollectionview中如果有横向滑动的列表，或者该uicollectionview嵌套在横向滑动的列表中就会出现滑动错乱，查看好像是因为自定义uitableview或者uicollectionview 是实现UIGestureRecognizerDelegate 的原因，有比较好的处理办法吗？

**Comment by ArchLL** [comment]
如果你不是在最后一个cell进行横向滑动，那么你可以参考HGCenterBaseTableView中的做法不让其他cell区域同时接收多个手势；如果你是在最后一个cell（嵌套区）的其中一个item下做横向滚动，那么这就不好处理了，你得想办法解决横向手势冲突的问题。因为这时候一般横向滑动是为了切换item，如果你其中一个item下对应的是collectionView并且是横向滑动的，这就比较尴尬，我这个库暂时不支持，业界也很少这么干的。

发自我的iPhone

**Comment by SeongBrave** [comment]
@ArchLL 嗯嗯，多谢了，我试试
